### ISSUE TITLE
CSS-like styles syntax

### ISSUE THREAD

**Issue by FrnchFrgg** [lvjr/tabularray#199]
I am the maintainer of the `cellprops` package (https://ctan.org/pkg/cellprops) which uses `mdwtab` to make tables smarter with CSS selectors and properties to control typesetting. At the time there was no reimplementation of tabulars in LaTεX3 and even though I have some preliminary work locally to do so I never got around to actually write it. (Ab)using another tabular package was easier.

Your project is very interesting, and I am interested in contributing. What do you think about having a CSS-like interface for most if not all settings, instead of reinventing ways of selecting cells and names for typesetting parameters ? Of course you cannot really deprecate the existing interfaces and maintaining 3 separate ones may be problematic, but maybe most old interfaces could be shims mapping to the newest one.

**Comment by lvjr** [comment]
Basically, I am quite satisfied with current interfaces of `tabularray` package. You could make `cellprops` package depend on it, which should be not that hard since there are enough style-setting functions in `tabularray` package. If you have any problems, you can start discussions here:
https://github.com/lvjr/tabularray/discussions
