### ISSUE TITLE
Drop support for \multicolumn and \multirow and remove them in version 2022

### ISSUE THREAD

**Issue by lvjr** [lvjr/tabularray#28]
`Tabularray` package tried its best to support legacy `\multicolumn` and `\multirow` commands by doing some dirty hack. But from a [question](https://tex.stackexchange.com/questions/603349/tabularray-and-new-command-for-multicolumn-cells) in tex.sx, it turns out that it's impossible to provide full support for these two commands, since these two commands conflict with the design of `tabularray` package.

Therefore I have decided to mark `\multicolumn` and `\multirow` as obsolete, and will remove them in version 2022. To make multicolumn or multirow cells, it's better to use `\SetCell` command in old interfaces, or `cell{i}{j}` in new interfaces.

Also, for backwards compatibility, I will include the last 2021 version of `tabularray` as `tabularray-2021.sty` in future releases for many years. Users could still use it for their old documents by `\usepackage{tabularray-2021}`.

**Comment by davidcarlisle** [comment]
Rather than `\usepackage{tabularray-2021}` you could consider making the saved old version available via the rollback argument so

`\usepackage{tabularray}[2021-06-01]`  (or `[v1]` or whatever string you want.)

see the examples where this is used in array or longtable for example.

One advantage of using this argument is that then both files are guarded by the same `\ver@tabularray` csname and so you can't load both. (Of course it's  possible to do the same without using the version declarations by making both packages define both ver@ csnames)

**Comment by lvjr** [comment]
Thanks. I did some tests with `longtable` package, If I write `\usepackage{longtable}[=v4.13]`, the kernel always need to load two `sty` files: first `longtable.sty` then `longtable-2020-01-07.sty`.

Is it possible for LaTeX kernel to support loading old package file directly? For example, if I write `\usepackage{tabularray}[v2021]` (note that there is no `=` before `v2021`), the kernel will load `tabularray-2021.sty` but not `tabularray.sty`.

**Comment by davidcarlisle** [comment]
well anything is possible of course and we tried a few variants but ended up with the indirection so that the option can be a version string or a date or whatever without directly affecting the filename. That does mean that you have to load the main file first to get the mappings. the file reading is stopped at that point so it is only the file load not actually interpreting the file that costs.  That is an issue but no worse that size1[012].clo meaning that the standard classes always use at least two file access.

```
Is it possible for LaTeX kernel to support loading old package file directly? For example, if I write \usepackage{tabularray}[v2021] (note that there is no = before v2021),
```

that particular syntax would be tricky as the trailing optional argument is not new it has been there since the start of latex2e and

`\usepackage{tabularray}[2021-01-01]`

without an `=` has always meant, give an error if the package found has an older date.

The newer `=` syntax to mean  load exactly the older specified version has to fit in with that. Adding a third variant in the same optional argument might be possible with a sufficiently careful syntax rule but would be quite hard to document.

**Comment by lvjr** [comment]
What about a new command such as `\useoldpackage` for this feature? Maybe I am asking too much. Just omit it.

I'm planning to keep the last version of `tabularray` package of each year and always include them in newer releases. With the current rollback scheme, I need to add one line of `\DeclareRelease` to `tabularray.sty` and remove unused `\DeclareRelease` in old `tabularray-20YY.sty` each year.  Adding one line of `\ver@tabularray` for one time seems simpler.

**Comment by davidcarlisle** [comment]
> I'm planning to keep the last version of tabularray package of each year

Really? that is millions of copies distributed to everyone all the time?  I
think that would be a very bad precedent to follow if all package authors
did that. it would mean the tex input tree gets much bigger each year.

We have only added rollback versions very rarely when there are breaking
changes (or in longtable case _any_ change, after a 25 year pause:-)

It is really easy these days to keep old distributions installed, anyone
with a critical document that needs to stay stable until it is submitted
can install texlive 2022 without uninstalling texlive 2021 and has no need
of the rollback at all, and can just use the older texlive if there is an
issue.
Even online editors like Overleaf make using an old texlive easy for people
who don't want to manage installations.


> Adding one line of ***@***.*** for one time seems simpler.

don't you have to do more?
if a class has \RequirePackage{tabularray}   and a user loads
\usepackage{tabularray-2021}  and then \usepackage{somethotherpackage} that
has \RequirePackage{tabularray-2020}

don't you end up with three copies loaded unless all three files define all
three ***@***.*** strings?

The idea behind the declarations was that the saved vesions could be
exactly the old copies  and you just need to add a declaration in the
current version whenever you add a rollback point.
I'm not going to claim it is the best system ever but for packages it works
better than \IncludeInRelease that we use in the format code.

**Comment by lvjr** [comment]
I have ever used NPM (NodeJS Package Manager), where users can install every old version of each package, also a package could require every old version of other packages. This avoids dependency hell. Seems it is still not the time for LaTeX world, where users suffer from package conflict after some updates from time to time. If we can resolve dependency problem, and make it easy to install old versions of packages, users don't need to install all the tex packages at the same time to minimize conflict. As far as I know, few users of other program languages need to install all the packages.

**Comment by passmore** [comment]
Rather than remove `\multicolumn` and `\multirow` altogether, you could leave them as they are now defined but deprecate them for future use, point out that full support isn't possible, and show how to use the new more powerful `cell{i}{j}` interface instead.
