### ISSUE TITLE
Column alignment specification cannot use with math mode.

### ISSUE THREAD

**Issue by gannaiju** [lvjr/tabularray#491]
The code below doesn't get desired result:

```latex
\documentclass{article}

\usepackage{tabularray}

\begin{document}
  \begin{tblr}{
      column{1} = {c},
      cells = {mode=math},
      }
    {a \\ bbb} & cc
  \end{tblr}
\end{document}
```

Please help me to fix it.
Thank you in advance.

**Comment by muzimuzhi** [comment]
It seems the implementation in version 2024A assumes content of math-mode cells are always single-line.

The first error your example raises is
```
! LaTeX Error: There's no line here to end.
```
It's raised by code on line 3788, in `\__tblr_get_vcell_and_sizes:NN`
https://github.com/lvjr/tabularray/blob/ec066c3cc7142f9b1cc4dfc2a5ed7e25fe3bafab/tabularray.sty#L3784-L3788

You can get the same error with `\vbox{\centering $a\\bbb$}`.

#492 shares the similar cause of current issue, but it's caused by some earlier code in `\__tblr_get_cell_text_real:nn`,
https://github.com/lvjr/tabularray/blob/ec066c3cc7142f9b1cc4dfc2a5ed7e25fe3bafab/tabularray.sty#L3708-L3721
so the width of multi-line math-mode cell `{\alpha \\ \alpha}` is measured by `\hbox{$\alpha \\ \alpha$}`, hence wider than expected.

To support multi-line math-mode cells, the package need to first split cell content by `\\`, then format each line if the cell is in math mode, finally measure size of cell.

**Comment by gannaiju** [comment]
@muzimuzhi Thank you.

1. The effected wanted is:
Set all cells in math mode,
then centering the contents in the first column.

2. As you had said, 

> To support multi-line math-mode cells, the package need to first split cell content by `\\`, then format each line if the cell is in math mode, finally measure size of cell. 

First, set all other cells except the multi-line cell in math mode, 
Second, set the alignment of the first column to center.
Last, set every line in multi-line cell in math mode separately.

The modified code is as below:

```latex
\documentclass{article}

\usepackage{tabularray}

\begin{document}
  \begin{tblr}{
      column{1} = {c},
      column{2} = {mode=math},
      }
    {$a$ \\ $bbb$} & cc
  \end{tblr}
\end{document}
```

**Comment by lvjr** [comment]
I have documented this limitation.
