### ISSUE TITLE
Trouble with colsep

### ISSUE THREAD

**Issue by dbitouze** [lvjr/tabularray#6]
In the following MCE, the first tabular is said to have a too small width: "need 16.45273pt more!" and, indeed, the second one is OK.
```latex
\documentclass{article}
\usepackage{tabularray}
\begin{document}
\noindent%
\begin{tblr}{colspec={p{\linewidth-2\rulewidth-2\tabcolsep}},vlines,colsep=5mm}
  Foobar
\end{tblr}

\noindent%
\begin{tblr}{colspec={p{\linewidth-2\rulewidth-2\tabcolsep-16.45273pt}},vlines,colsep=5mm}
  Foobar
\end{tblr}
\end{document}
```
But I cannot understand where this `16.45273pt` is coming from and the following attempt to retrieve the `colsep` dimension fails (in the second tabular, `leftsep` and `rightsep` are claimed to be `14.22636pt` and `@vline-width` is claimed to be `0.4pt`).
```latex
\documentclass{article}
\usepackage{tabularray}
\begin{document}
\noindent%
\ExplSyntaxOn
\dim_new:N \l_leftsep_dim
\dim_new:N \l_rightsep_dim
\dim_new:N \l_vline_width_dim
\begin{tblr}{rowspec={Q[c,m]},colspec={p{\linewidth-2\rulewidth-2\tabcolsep}},vlines,hlines}
  \dim_set:Nn \l_leftsep_dim {
    \__tblr_prop_item:ne {column} { [\l__tblr_j_tl] / leftsep}
  }
  \dim_show:N \l_leftsep_dim
  \dim_set:Nn \l_rightsep_dim {
    \__tblr_prop_item:ne {column} { [\l__tblr_j_tl] / rightsep}
  }
  \dim_show:N \l_rightsep_dim
  \dim_set:Nn \l_vline_width_dim {
    \__tblr_prop_item:ne {vline} { [\l__tblr_j_tl] / @vline-width }
  }
  \dim_show:N \l_vline_width_dim
  Foobar
\end{tblr}
\par
\noindent%
\begin{tblr}{rowspec={Q[c,m]},colspec={p{\linewidth-2\rulewidth-2\tabcolsep-16.45273pt}},vlines,hlines,colsep=5mm}
  \dim_set:Nn \l_leftsep_dim {
    \__tblr_prop_item:ne {column} { [\l__tblr_j_tl] / leftsep}
  }
  \dim_show:N \l_leftsep_dim
  \dim_set:Nn \l_rightsep_dim {
    \__tblr_prop_item:ne {column} { [\l__tblr_j_tl] / rightsep}
  }
  \dim_show:N \l_rightsep_dim
  \dim_set:Nn \l_vline_width_dim {
    \__tblr_prop_item:ne {vline} { [\l__tblr_j_tl] / @vline-width }
  }
  \dim_show:N \l_vline_width_dim
  Foobar
\end{tblr}
\ExplSyntaxOff
\end{document}
```
Is it possible, when `colsep` (or either `leftsep` or `rightsep`) is set, to get the dimension which has to be subtracted to the tabular width in order to get the same width as when `colsep` is not used?

**Comment by lvjr** [comment]
Why not use "width=\linewidth, colspec={|X|}"?


--


在 2021-05-21 23:50:40，"Denis Bitouzé" ***@***.***> 写道：


In the following MCE, the first tabular is said to have a too small width: "need 16.45273pt more!" and, indeed, the second one is OK.

\documentclass{article}
\usepackage{tabularray}
\begin{document}
\noindent%\begin{tblr}{colspec={p{\linewidth-2\rulewidth-2\tabcolsep}},vlines,colsep=5mm}
  Foobar
\end{tblr}

\noindent%\begin{tblr}{colspec={p{\linewidth-2\rulewidth-2\tabcolsep-16.45273pt}},vlines,colsep=5mm}
  Foobar
\end{tblr}
\end{document}

But I cannot understand where this 16.45273pt is coming from and the following attempt to retrieve the colsep dimension fails (in the second tabular, leftsep and rightsep are claimed to be 14.22636pt and @vline-width is claimed to be 0.4pt).

\documentclass{article}
\usepackage{tabularray}
\begin{document}
\noindent%\ExplSyntaxOn\dim_new:N \l_leftsep_dim
\dim_new:N \l_rightsep_dim
\dim_new:N \l_vline_width_dim
\begin{tblr}{rowspec={Q[c,m]},colspec={p{\linewidth-2\rulewidth-2\tabcolsep}},vlines,hlines}
  \dim_set:Nn \l_leftsep_dim {
    \__tblr_prop_item:ne {column} { [\l__tblr_j_tl] / leftsep}
  }
  \dim_show:N \l_leftsep_dim
  \dim_set:Nn \l_rightsep_dim {
    \__tblr_prop_item:ne {column} { [\l__tblr_j_tl] / rightsep}
  }
  \dim_show:N \l_rightsep_dim
  \dim_set:Nn \l_vline_width_dim {
    \__tblr_prop_item:ne {vline} { [\l__tblr_j_tl] / @vline-width }
  }
  \dim_show:N \l_vline_width_dim
  Foobar
\end{tblr}

\noindent%\begin{tblr}{rowspec={Q[c,m]},colspec={p{\linewidth-2\rulewidth-2\tabcolsep-16.45273pt}},vlines,hlines,colsep=5mm,leftsep=5mm}
  \dim_set:Nn \l_leftsep_dim {
    \__tblr_prop_item:ne {column} { [\l__tblr_j_tl] / leftsep}
  }
  \dim_show:N \l_leftsep_dim
  \dim_set:Nn \l_rightsep_dim {
    \__tblr_prop_item:ne {column} { [\l__tblr_j_tl] / rightsep}
  }
  \dim_show:N \l_rightsep_dim
  \dim_set:Nn \l_vline_width_dim {
    \__tblr_prop_item:ne {vline} { [\l__tblr_j_tl] / @vline-width }
  }
  \dim_show:N \l_vline_width_dim
  Foobar
\end{tblr}
\ExplSyntaxOff\end{document}

Is it possible, when colsep (or either leftsep or rightsep) is set, to get the dimension which has to be subtracted to the tabular width in order to get the same width as when colsep is not used?

**Comment by dbitouze** [comment]
Indeed, better solution: thanks!

**Comment by lvjr** [comment]
By the way, you can use \SetTblrTracing{all} outside tblr environment to show all dimensions.

**Comment by dbitouze** [comment]
> By the way, you can use `\SetTblrTracing{all}` outside `tblr` environment to show all dimensions.

Ah, nice to know! (BTW, only in the `.log` file). IMO, it is worth to document this public macro.

**Comment by lvjr** [comment]
Yes, I will add it to the manual later.

**Comment by dbitouze** [comment]
Could be nice to provide a (starred?) variant of this command that displays all dimensions in the terminal or even in the document itself: displaying them only in the `.log` is not very handy since the user has to search for them in this usually very verbose file.

**Comment by lvjr** [comment]
Tracing commands are mainly for package developer. It's conventional to write tracing data to log files. In tabularray you may choose what you need to trace: for example, \SetTblrTracing{+column} would only trace column dimensions. See the last section of the source code for all available tracing options.
