### ISSUE TITLE
Align outside text and tblr at any row or border

### ISSUE THREAD

**Issue by cdacl** [lvjr/tabularray#72]
When I use `valign=b` or `[b]` to set the outer valign of `tblr` composed by multiline cells, It does not work:

```
a \begin{tblr}[b]{vlines}
 \firsthline
 {more \\ tblr \\ line } \\
 \lasthline
\end{tblr} line.

```
The output:

![1](https://user-images.githubusercontent.com/87848848/129648465-4e5220d0-2c2a-4d02-8cee-0dc411d2b43b.png)

Another question: can I use the normal `hlines` to get the same outer valign behavior as  the `firsthline` / `lasthline` ?
Thanks.

**Comment by lvjr** [comment]
The `\firsthline` and `\lasthline` commands are undoumented, because I have not decided the final interfaces for baseline alignment.

At this time there is an undocumented `baseline` option for `hline` (only works for first and last hlines):

````latex
\documentclass{article}
\usepackage{tabularray}
\begin{document}

a \begin{tblr}[t]{vlines,hlines,hline{1}={baseline=below}}
 more \\ tblr \\ line \\
\end{tblr} line.

a \begin{tblr}[b]{vlines,hlines,hline{Z}={baseline=above}}
 more \\ tblr \\ line \\
\end{tblr} line.

\end{document}
````
![image](https://user-images.githubusercontent.com/4239949/129654966-e85f242f-4b2d-4b8b-bc89-e6183b6cfb1e.png)

But **DON'T** use it in your real documents. I am planning to remove `\firsthline` and `\lasthline` (also `baseline` option for `hline`) since they doesn't provide a perfect general solution for baseline alignment.

I thinks it is better to move baseline option to outer specifications and merge it with `valign` option. You will be able to write for example `valign=row{2}` to align text with the second row of the table, and  `valign=hline{3}` to align text with the third hline. The idea is inspired by `nicematrix` package.

**Comment by cdacl** [comment]
It's cool. Thank you very much!

**Comment by lvjr** [comment]
For your original probelm, TeX aligns boxes in a row at baseline. The default vertical alignment for cells are `t`, so the baseline is at the first row. You need to change the alignment to `b`.
````latex
\documentclass{article}
\usepackage{tabularray}
\begin{document}
a \begin{tblr}[b]{vlines,row{1}={b}}
 \firsthline
 {more \\ tblr \\ line } \\
 \lasthline
\end{tblr} line.
\end{document} 
````
![image](https://user-images.githubusercontent.com/4239949/129661211-b71ed154-75ec-45f0-9315-8c839327be02.png)

But the table is `0.4pt` above the baseline at present, which is a bug to be fixed.

**Comment by lvjr** [comment]
See also this TeX.SE question:
https://tex.stackexchange.com/questions/608959/tabularray-align-tabular-with-text
